"""init tx 2

Revision ID: 57add944252d
Revises: ce7bb07752af
Create Date: 2025-12-25 22:43:25.306506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57add944252d'
down_revision = 'ce7bb07752af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('from_account',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('from_account',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)

    # ### end Alembic commands ###
