"""init db

Revision ID: 5db23e31b135
Revises: 57add944252d
Create Date: 2026-01-05 22:09:49.069141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5db23e31b135'
down_revision = '57add944252d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_guests_username'), ['username'], unique=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_foreign_key(None, 'guests', ['id'], ['id'])
        batch_op.drop_column('username')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('second_name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_foreign_key(None, 'guests', ['id'], ['id'])
        batch_op.drop_column('username')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('second_name')
        batch_op.drop_column('created_at')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
        batch_op.add_column(sa.Column('second_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
        batch_op.add_column(sa.Column('second_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=65), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guests_username'))
        batch_op.drop_index(batch_op.f('ix_guests_email'))

    op.drop_table('guests')
    # ### end Alembic commands ###
